### ISSUE TITLE
Get researcher business case approval

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/documentation#33] opened 2018-10-15 09:52 UTC
requires #32

All of the documents for this can be found here: https://drive.google.com/drive/u/0/folders/11IKd3-pDKiMwOuoNj9uZqx6y3CHrwdCn

**Comment by tatyree** [comment] 2018-11-02 10:47
@UmeshxSolanki has made a number of comments on the case.  However, none of these will affect Mike Driver's approval, as this essentially a duplicate of the developer business case, which has already been approved, so I'm going to go ahead and ship it. 

@UmeshxSolanki, is it safe to say your main concerns focus around deliverables and reporting?  If I'm correct about that, then these form part of a larger, ongoing conversation with the SLT about how we reconcile digital process management with historic civil service process management.

**Comment by tatyree** [comment] 2018-11-02 11:08
Sent to Sophia Jenkins for Mike Driver's approval.  She is on holiday until Monday, November 5th, so moving this back to blocked.

**Comment by tatyree** [comment] 2018-11-06 11:21
[researcher approval.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55798f28b5a4851c00ef7595/125516c66e82c728ace21e0d46fa9189268391aa87ecad03a54de0862650267f6b48e13b628ae92dbc56395b4d5a1cfe13595815adf18f79f3e035708a5d5fbcd56a5625902f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e38a8a4f3d1c021e8dfe5c27ed.pdf)

**Closed by tatyree** 2018-11-06 11:21 UTC
Labels: blocked, contracts

**Comment by tatyree** [comment] 2018-11-07 12:29
Approval received via email to me.
